// Generated by CoffeeScript 1.3.3
(function() {
  var getAttendance, getDiscipline, getMorality, global, resetData, resetSchoolYearSeme;

  global = {};

  jQuery(function() {
    gadget.autofit(document.getElementById("widget"));
    gadget.onSizeChanged(function(size) {
      return $("#behavior").height(size.height - 110);
    });
    $("#children-list").on("click", "a", function(e) {
      $('#children-list li[class=active]').removeClass('active');
      $(this).parent().addClass('active');
      global.student = global.students[$(this).attr("children-index")];
      global.behavior = {
        schoolYear: global.schoolYear,
        semester: global.semester
      };
      $("#behavior #discipline tbody").html("");
      resetSchoolYearSeme();
      resetData();
      getMorality();
      getAttendance();
      return getDiscipline();
    });
    $("#behavior .btn-group").on("click", ".btn", function(e) {
      if (global.student != null) {
        global.behavior = {
          schoolYear: $(this).attr("school-year"),
          semester: $(this).attr("semester")
        };
        resetData();
        getMorality();
        getAttendance();
        return getDiscipline();
      }
    });
    $("#behavior").hover(function() {
      return $(this).css("overflow", "auto");
    }, function() {
      return $(this).css("overflow", "hidden");
    });
    $("#morality a[my-toggle=collapse]").click(function() {
      $("#morality-container").slideToggle(500);
      return false;
    });
    $("#discipline a[my-toggle=collapse]").click(function() {
      $("#collapseD").slideToggle(500);
      return false;
    });
    $("#attendance").on("click", ".my-content a", function() {
      var id;
      id = $(this).attr("data-action") || "";
      if (id) {
        $("#attendance .accordion-body").addClass('hide');
        if ($(this).find('i').size()) {
          return $(this).find('i').remove();
        } else {
          $("#attendance").find('i').remove();
          $(this).find("h5").append('<i class="icon-eye-open"></i>');
          return $("#" + id).removeClass("hide");
        }
      }
    });
    gadget.getContract("ischool.AD.parent").send({
      service: "_.GetMorality",
      body: "",
      result: function(response, error, xhr) {
        if (error != null) {
          return $("#mainMsg").html("<div class='alert alert-error'>\n  <button class='close' data-dismiss='alert'>×</button>\n  <strong>呼叫服務失敗或網路異常，請稍候重試!</strong>(GetMorality)\n</div>");
        } else {
          return global.morality = response;
        }
      }
    });
    return gadget.getContract("ischool.AD.parent").send({
      service: "_.GetCurrentSemester",
      body: "",
      result: function(response, error, xhr) {
        if (error != null) {
          return $("#mainMsg").html("<div class='alert alert-error'>\n  <button class='close' data-dismiss='alert'>×</button>\n  <strong>呼叫服務失敗或網路異常，請稍候重試!</strong>(GetCurrentSemester)\n</div>");
        } else {
          global.schoolYear = response.Current.SchoolYear;
          global.semester = response.Current.Semester;
          return gadget.getContract("ischool.AD.parent").send({
            service: "_.GetStudentInfo",
            body: "",
            result: function(response, error, xhr) {
              var items, _ref;
              if (error != null) {
                return $("#mainMsg").html("<div class='alert alert-error'>\n  <button class='close' data-dismiss='alert'>×</button>\n  <strong>呼叫服務失敗或網路異常，請稍候重試!</strong>(GetStudentInfo)\n</div>");
              } else {
                if (((_ref = response.Result) != null ? _ref.Student : void 0) != null) {
                  resetData();
                  global.students = $(response.Result.Student);
                  items = [];
                  global.students.each(function(index, student) {
                    return items.push("<li " + (index === 0 ? " class='active'" : '') + ">\n  <a href='#' children-index='" + index + "'>" + this.StudentName + "</a>\n</li>");
                  });
                  return $("#children-list").html(items.join("")).find('a:first').trigger('click');
                }
              }
            }
          });
        }
      }
    });
  });

  resetSchoolYearSeme = function() {
    var items, student;
    student = global.student;
    items = [];
    if (student.SemsHistory != null) {
      $(student.SemsHistory).each(function(index, item) {
        if (item.History != null) {
          return $(item.History).each(function(e) {
            if (!(this.SchoolYear === global.schoolYear && this.Semester === global.semester)) {
              return items.push("<button class='btn btn-large' school-year='" + this.SchoolYear + "' semester='" + this.Semester + "'>" + (this.SchoolYear + '' + this.Semester) + "</button>");
            }
          });
        }
      });
      items.push("<button class='btn btn-large active' school-year='" + global.schoolYear + "' semester='" + global.semester + "'>" + (global.schoolYear + '' + global.semester) + "</button>");
      return $("#behavior .btn-group").html(items.reverse().join(""));
    }
  };

  resetData = function() {
    $("#behavior #morality tbody").html("");
    $("#morality-view").addClass("hide");
    $("#behavior #attendance .my-content").html("");
    $("#behavior #discipline tbody").html("");
    $("#merit-a").html("<span class='badge'>0</span>");
    $("#merit-b").html("<span class='badge'>0</span>");
    $("#merit-c").html("<span class='badge'>0</span>");
    $("#demerit-a").html("<span class='badge'>0</span>");
    $("#demerit-b").html("<span class='badge'>0</span>");
    $("#demerit-c").html("<span class='badge'>0</span>");
    $("#demerit-d").html("");
    return $("#discipline-view").addClass("hide");
  };

  getMorality = function() {
    return gadget.getContract("ischool.AD.parent").send({
      service: "_.GetMoralScore",
      body: "<Request>\n  <StudentID>" + global.student.StudentID + "</StudentID>\n  <SchoolYear>" + global.behavior.schoolYear + "</SchoolYear>\n  <Semester>" + global.behavior.semester + "</Semester>\n</Request>",
      result: function(response, error, xhr) {
        var items, _ref, _ref1;
        if (error != null) {
          return $("#mainMsg").html("<div class='alert alert-error'>\n  <button class='close' data-dismiss='alert'>×</button>\n  <strong>呼叫服務失敗或網路異常，請稍候重試!</strong>(GetMoralScore)\n</div>");
        } else {
          items = [];
          if (((_ref = response.Result) != null ? _ref.SbComment : void 0) != null) {
            items.push("<tr>\n  <th><span>導師評語</span></th>\n  <td><span>" + (this.response.Result.SbComment || '') + "</span></td>\n</tr>");
          }
          if (((_ref1 = global.morality.Response) != null ? _ref1.Morality : void 0) != null) {
            $(global.morality.Response.Morality).each(function() {
              var that, tmpFace, _ref2, _ref3, _ref4;
              items.push("<tr>\n  <th><span>" + (this.Face || '') + "</span></th>");
              that = this;
              tmpFace = '';
              if (((_ref2 = response.Result) != null ? (_ref3 = _ref2.DailyLifeScore) != null ? (_ref4 = _ref3.Content) != null ? _ref4.Morality : void 0 : void 0 : void 0) != null) {
                $(response.Result.DailyLifeScore.Content.Morality).each(function() {
                  if (this.Face === that.Face) {
                    tmpFace = this['@text'];
                    return false;
                  }
                });
              }
              return items.push("<td><span>" + (tmpFace || '') + "</span></td>");
            });
            items.push("</tr>");
            $("#morality-view").removeClass("hide");
            $("#behavior #morality tbody").html(items.join(""));
            return $("#behavior #morality h2").html("德行");
          } else {
            return $("#behavior #morality tbody").html("<tr><td>目前無資料</td></tr>");
          }
        }
      }
    });
  };

  getAttendance = function() {
    return gadget.getContract("ischool.AD.parent").send({
      service: "_.GetAttendanceRecord",
      body: "<Request>\n  <StudentID>" + global.student.StudentID + "</StudentID>\n  <SchoolYear>" + global.behavior.schoolYear + "</SchoolYear>\n  <Semester>" + global.behavior.semester + "</Semester>\n</Request>",
      result: function(response, error, xhr) {
        var absences, ii, info, items, name, tmp, _ref;
        if (error != null) {
          return $("#mainMsg").html("<div class='alert alert-error'>\n  <button class='close' data-dismiss='alert'>×</button>\n  <strong>呼叫服務失敗或網路異常，請稍候重試!</strong>(GetAttendanceRecord)\n</div>");
        } else {
          absences = {};
          if (((_ref = response.Result) != null ? _ref.Attendance : void 0) != null) {
            $(response.Result.Attendance).each(function() {
              var occurDate, ret, that;
              that = this;
              occurDate = that.OccurDate;
              ret = {};
              $(this.Detail.Attendance.Period).each(function() {
                if (!(absences[this['AbsenceType']] != null)) {
                  absences[this['AbsenceType']] = 0;
                  absences[this['AbsenceType'] + '_info'] = [];
                }
                absences[this['AbsenceType']] += 1;
                if (!(ret[this['AbsenceType']] != null)) {
                  return ret[this['AbsenceType']] = this['@text'];
                } else {
                  return ret[this['AbsenceType']] += ', ' + this['@text'];
                }
              });
              return $.each(ret, function(key, value) {
                var detail;
                detail = {
                  OccurDate: occurDate,
                  Periods: value
                };
                return absences[key + '_info'].push(detail);
              });
            });
          }
          items = [];
          info = [];
          ii = 0;
          for (name in absences) {
            if (name.indexOf("_info") < 0) {
              ii += 1;
              items.push("<li class='span2'>\n  <a href=\"javascript:void(0);\" data-action=\"attendance" + ii + "\">\n    <div class='thumbnail my-thumbnail-white'>\n      <div class='my-subthumbnail-top'>\n        <span class='badge badge-warning'>" + (absences[name] || '') + "</span>\n      </div>\n      <div class='caption my-subthumbnail-bottom'>\n        <h5>" + (name || '') + "</h5>\n      </div>\n    </div>\n  </a>\n</li>");
              tmp = [];
              $(absences[name + '_info']).each(function() {
                return tmp.push("<tr>\n  <td>" + (this.OccurDate || '') + "</td>\n  <td>" + (this.Periods || '') + "</td>\n  <td><span>" + (name || '') + "</span></td>\n</tr>");
              });
              tmp.reverse();
              info.push("<div id=\"attendance" + ii + "\" class=\"accordion-body hide\">\n    <table class=\"table table-striped\">\n      <tbody>\n        " + (tmp.join('')) + "\n      </tbody>\n    </table>\n</div>");
            }
          }
          if (items.join("") === "") {
            return $("#behavior #attendance .my-content").html("目前無資料");
          } else {
            $("#behavior #attendance .my-content").html("<ul class='thumbnails'>\n  " + (items.join("")) + "\n</ul>\n<div>\n  " + (info.join("")) + "\n</div>");
            $("#attendance a:first").trigger('click');
            return $('#attendance .accordion-body').alternateScroll();
          }
        }
      }
    });
  };

  getDiscipline = function() {
    return gadget.getContract("ischool.AD.parent").send({
      service: "_.GetDisciplineRecord",
      body: "<Request>\n  <StudentID>" + global.student.StudentID + "</StudentID>\n  <SchoolYear>" + global.behavior.schoolYear + "</SchoolYear>\n  <Semester>" + global.behavior.semester + "</Semester>\n</Request>",
      result: function(response, error, xhr) {
        var items, sum_merit, _ref;
        if (error != null) {
          return $("#mainMsg").html("<div class='alert alert-error'>\n  <button class='close' data-dismiss='alert'>×</button>\n  <strong>呼叫服務失敗或網路異常，請稍候重試!</strong>(GetDisciplineRecord)\n</div>");
        } else {
          items = [];
          if (((_ref = response.Result) != null ? _ref.Discipline : void 0) != null) {
            sum_merit = {
              ma: 0,
              mb: 0,
              mc: 0,
              da: 0,
              db: 0,
              dc: 0,
              dd: 0
            };
            $(response.Result.Discipline).each(function() {
              var merit, merit_clear;
              merit = {
                a: 0,
                b: 0,
                c: 0
              };
              if (this.MeritFlag === "1") {
                if (!isNaN(parseInt(this.Detail.Discipline.Merit.A, 10))) {
                  sum_merit.ma += merit.a = parseInt(this.Detail.Discipline.Merit.A, 10);
                }
                if (!isNaN(parseInt(this.Detail.Discipline.Merit.B, 10))) {
                  sum_merit.mb += merit.b = parseInt(this.Detail.Discipline.Merit.B, 10);
                }
                if (!isNaN(parseInt(this.Detail.Discipline.Merit.C, 10))) {
                  sum_merit.mc += merit.c = parseInt(this.Detail.Discipline.Merit.C, 10);
                }
                return items.push("<tr>\n  <td class=\"my-flags\">\n    <span class=\"badge " + (merit.a !== 0 ? "badge-success" : "") + "\">" + merit.a + "</span>\n    <br />大功\n  </td>\n  <td class=\"my-flags\">\n    <span class=\"badge " + (merit.b !== 0 ? "badge-success" : "") + "\">" + merit.b + "</span>\n    <br />小功\n  </td>\n  <td class=\"my-flags\">\n    <span class=\"badge " + (merit.c !== 0 ? "badge-success" : "") + "\">" + merit.c + "</span>\n    <br />嘉獎\n  </td>\n  <td>\n    <span>" + (this.OccurDate.substr(0, 10)) + "</span>\n    <br/>\n    <span>" + this.Reason + "</span>\n  </td>\n</tr>");
              } else if (this.MeritFlag === "2") {
                sum_merit.dd += 1;
                return items.push("<tr>\n  <td colspan=\"3\" class=\"my-detention\">留校察看</td>\n  <td class=\"my-detention-text\">\n    <span>" + (this.OccurDate.substr(0, 10)) + "</span>\n    <br/>\n    <span>" + (this.Reason || '') + "</span>\n  </td>\n</tr>");
              } else {
                if (!isNaN(parseInt(this.Detail.Discipline.Demerit.A, 10))) {
                  merit.a = parseInt(this.Detail.Discipline.Demerit.A, 10);
                }
                if (!isNaN(parseInt(this.Detail.Discipline.Demerit.B, 10))) {
                  merit.b = parseInt(this.Detail.Discipline.Demerit.B, 10);
                }
                if (!isNaN(parseInt(this.Detail.Discipline.Demerit.C, 10))) {
                  merit.c = parseInt(this.Detail.Discipline.Demerit.C, 10);
                }
                merit_clear = this.Detail.Discipline.Demerit.Cleared;
                if (merit_clear !== '是') {
                  sum_merit.da += merit.a;
                  sum_merit.db += merit.b;
                  sum_merit.dc += merit.c;
                }
                return items.push("<tr>\n  <td class=\"my-flags\">\n    <span class=\"badge " + (merit.a !== 0 && merit_clear === "是" ? "badge-warning" : (merit.a !== 0 ? "badge-important" : "")) + "\">" + merit.a + "</span>\n    <br />大過\n  </td>\n  <td class=\"my-flags\">\n    <span class=\"badge " + (merit.b !== 0 && merit_clear === '是' ? "badge-warning" : (merit.b !== 0 ? "badge-important" : "")) + "\">" + merit.b + "</span>\n    <br />小過\n  </td>\n  <td class=\"my-flags\">\n    <span class=\"badge " + (merit.c !== 0 && merit_clear === '是' ? "badge-warning" : (merit.c !== 0 ? "badge-important" : "")) + "\">" + merit.c + "</span>\n    <br />警告\n  </td>\n  <td>\n    " + (this.Detail.Discipline.Demerit.Cleared === '是' ? "<span class='my-offset'>" + (this.Detail.Discipline.Demerit.ClearDate.substr(0, 10).replace(/\//ig, "-")) + " 已銷過<br/>" + (this.Detail.Discipline.Demerit.ClearReason || '') + "</span><br/>" : "") + "\n    <span>" + (this.OccurDate.substr(0, 10)) + "</span>\n    <br/>\n    <span>" + (this.Reason || '') + "</span>\n  </td>\n</tr>");
              }
            });
            $("#merit-a").html("<span class='badge " + (sum_merit.ma !== 0 ? "badge-success" : "") + "'>" + sum_merit.ma + "</span>");
            $("#merit-b").html("<span class='badge " + (sum_merit.mb !== 0 ? "badge-success" : "") + "'>" + sum_merit.mb + "</span>");
            $("#merit-c").html("<span class='badge " + (sum_merit.mc !== 0 ? "badge-success" : "") + "'>" + sum_merit.mc + "</span>");
            $("#demerit-a").html("<span class='badge " + (sum_merit.da !== 0 ? "badge-important" : "") + "'>" + sum_merit.da + "</span>");
            $("#demerit-b").html("<span class='badge " + (sum_merit.db !== 0 ? "badge-important" : "") + "'>" + sum_merit.db + "</span>");
            $("#demerit-c").html("<span class='badge " + (sum_merit.dc !== 0 ? "badge-important" : "") + "'>" + sum_merit.dc + "</span>");
            if (sum_merit.dd > 0) {
              $("#demerit-d").html("<li class=\"span12\">\n  <div class=\"thumbnail my-thumbnail-white\">\n    <div class=\"caption my-surveillance\">\n      <h5>留校察看</h5>\n    </div>\n  </div>\n</li>");
            }
            $("#discipline-view").removeClass("hide");
            return $("#discipline tbody").html(items.join(""));
          }
        }
      }
    });
  };

}).call(this);
