// Generated by CoffeeScript 1.3.3
(function() {
  var current_index, experience, preview_detail, query_student, sharing, students;

  $(function() {
    var all_dept;
    all_dept = [];
    gadget.getContract("emba.student").send({
      service: "default.GetDepartmentGroup",
      body: "",
      result: function(response, error, http) {
        var items;
        if (response.Result != null) {
          items = ["<li><a herf='#'>系所組別</a></li>"];
          $(response.Result.Department).each(function() {
            return items.push("<li><a herf='#'>" + this.Name + "</a></li>");
          });
          all_dept = items;
          $("ul[target='department-options']").html(items.join(""));
          $("ul[target='department-options'] a").unbind("click");
          return $("ul[target='department-options'] a").on({
            click: function(e) {
              e.preventDefault();
              return $("span[target='department']").html($(this).html());
            }
          });
        }
      }
    });
    $("a[target='query']").click(function(e) {
      e.preventDefault();
      return query_student();
    });
    return $("input[target='enroll-year']").change(function() {
      $("span[target='department']").html("系所組別");
      $("ul[target='department-options']").html("");
      if ($(this).val() !== "") {
        return gadget.getContract("emba.student").send({
          service: "default.GetEnrollYearDepartmentGroup",
          body: "<Request><Condition><EnrollYear>" + ($(this).val()) + "</EnrollYear></Condition></Request>",
          result: function(response, error, http) {
            var items;
            if (response.Result != null) {
              items = ["<li><a herf='#'>系所組別</a></li>"];
              $(response.Result.Department).each(function() {
                return items.push("<li><a herf='#'>" + this.Name + "</a></li>");
              });
              $("ul[target='department-options']").html(items.join(""));
              $("ul[target='department-options'] a").unbind("click");
              return $("ul[target='department-options'] a").on({
                click: function(e) {
                  e.preventDefault();
                  return $("span[target='department']").html($(this).html());
                }
              });
            }
          }
        });
      } else {
        $("ul[target='department-options']").html(all_dept.join(""));
        $("ul[target='department-options'] a").unbind("click");
        return $("ul[target='department-options'] a").on({
          click: function(e) {
            e.preventDefault();
            return $("span[target='department']").html($(this).html());
          }
        });
      }
    });
  });

  students = [];

  current_index = 0;

  experience = [];

  sharing = {};

  query_student = function() {
    $("table[target='student-detail'] tbody").html("");
    if ($("input[target='student-name']").val() !== "" || $("input[target='company-name']").val() !== "" || $("input[target='enroll-year']").val() !== "" || $("span[target='department']").html() !== "系所組別") {
      return gadget.getContract("emba.student").send({
        service: "public.QueryStudents",
        body: "<Request>\n	<All/>\n	" + ($("input[target='student-name']").val() !== "" ? "<Name>%" + ($("input[target='student-name']").val()) + "%</Name>" : "") + "\n	" + ($("input[target='company-name']").val() !== "" ? "<CompanyName>%" + ($("input[target='company-name']").val()) + "%</CompanyName><CompanySharing>true</CompanySharing>" : "") + "\n	" + ($("input[target='enroll-year']").val() !== "" ? "<EnrollYear>%" + ($("input[target='enroll-year']").val()) + "%</EnrollYear>" : "") + "\n	" + ($("span[target='department']").html() !== "系所組別" ? "<DepartmentName>%" + ($("span[target='department']").html()) + "%</DepartmentName>" : "") + "\n</Request>",
        result: function(response, error, http) {
          var items;
          if (response.Result != null) {
            items = [];
            students = $(response.Result.Student);
            students.each(function(index, item) {
              return items.push("<tr>\n	<td>" + item.EnrollYear + "</td>\n	<td>" + item.ClassName + "</td>\n	<td><a href='#' target='detail' index='" + index + "'>" + item.Name + "</a></td>\n	<td>" + item.Gender + "</td>\n	<td>" + item.DepartmentName + "</td>\n</tr>");
            });
            $("table[target='student-list'] tbody").html(items.join(""));
            return $("table[target='student-list'] a[target='detail']").click(function(e) {
              e.preventDefault();
              experience = [];
              sharing = {
                "Name": "true",
                "Gender": "true",
                "Birthdate": "false",
                "Custodian": "false",
                "CustodianPhone": "false",
                "ContactPhone": "false",
                "PermanentPhone": "false",
                "公司電話": "false",
                "行動電話2": "false",
                "秘書電話": "false",
                "SMSPhone": "false",
                "EmailList": {
                  "Email1": "false",
                  "Email2": "false",
                  "Email3": "false",
                  "Email4": "false",
                  "Email5": "false"
                },
                "ContactAddress": "false",
                "PermanentAddress": "false"
              };
              current_index = $(this).attr("index");
              return gadget.getContract("emba.student").send({
                service: "public.QueryStudentExperience",
                body: "<Request>\n	<StudentID>" + students[current_index].StudentID + "</StudentID>\n</Request>",
                result: function(response, error, http) {
                  if (response.Result != null) {
                    experience = response.Result.Experience;
                  }
                  return gadget.getContract("emba.student").send({
                    service: "public.QueryStudentBrief",
                    body: "<Request>\n	<StudentID>" + students[current_index].StudentID + "</StudentID>\n</Request>",
                    result: function(response, error, http) {
                      var _ref, _ref1;
                      if ((((_ref = response.Result) != null ? (_ref1 = _ref.DataSharing) != null ? _ref1.DataSharing : void 0 : void 0) != null)) {
                        sharing = response.Result.DataSharing.DataSharing;
                        $(response.Result.DataSharing.DataSharing.OtherPhoneList.PhoneNumber).each(function(index, item) {
                          return sharing[item.title] = item['@text'];
                        });
                      }
                      return preview_detail();
                    }
                  });
                }
              });
            });
          }
        }
      });
    }
  };

  preview_detail = function() {
    var experience_content, student;
    student = students[current_index];
    experience_content = [];
    $(experience).each(function() {
      if (this.IsSharing === "t") {
        return experience_content.push("<tr>\n	<th class=\"myth\"><span>公司</span></th>\n	<td><span>" + (this.CompanyName || '本人未公開資訊') + "</span></td>\n</tr>\n<tr>\n	<th class=\"myth\"><span>職稱</span></th>\n	<td><span>" + (this.Position || '本人未公開資訊') + "</span></td>\n</tr>");
      }
    });
    if (experience_content.length === 0) {
      experience_content.push("<tr>\n	<th class=\"myth\"><span>公司</span></th>\n	<td><span>本人未公開資訊</span></td>\n</tr>\n<tr>\n	<th class=\"myth\"><span>職稱</span></th>\n	<td><span>本人未公開資訊</span></td>\n</tr>");
    }
    return $("table[target='student-detail'] tbody").html("<tr>\n	<th class=\"myth\"><span>姓名</span></th>\n	<td><span>" + student.Name + "</span></td>\n</tr>\n<tr>\n	<th class=\"myth\"><span>性別</span></th>\n	<td><span>" + student.Gender + "</span></td>\n</tr>\n" + (experience_content.join("")) + "\n<tr>\n	<th class=\"myth\"><span>公司電話</span></th>\n	<td><span>" + (sharing['公司電話'] === "true" ? student.OfficePhone : '本人未公開資訊') + "</span></td>\n</tr>\n<tr>\n	<th class=\"myth\"><span>行動電話1</span></th>\n	<td><span>" + (sharing['SMSPhone'] === "true" ? student.SMSPhone1 : '本人未公開資訊') + "</span></td>\n</tr>\n<tr>\n	<th class=\"myth\"><span>行動電話2</span></th>\n	<td><span>" + (sharing['行動電話2'] === "true" ? student.SMSPhone2 : '本人未公開資訊') + "</span></td>\n</tr>\n<tr>\n	<th class=\"myth\"><span>Email1</span></th>\n	<td><span>" + (sharing.EmailList['Email1'] === "true" ? student.Email1 : '本人未公開資訊') + "</span></td>\n</tr>\n<tr>\n	<th class=\"myth\"><span>Email2</span></th>\n	<td><span>" + (sharing.EmailList['Email2'] === "true" ? student.Email2 : '本人未公開資訊') + "</span></td>\n</tr>\n<tr>\n	<th class=\"myth\"><span>Email3</span></th>\n	<td><span>" + (sharing.EmailList['Email3'] === "true" ? student.Email3 : '本人未公開資訊') + "</span></td>\n</tr>\n<tr>\n	<th class=\"myth\"><span>Email4</span></th>\n	<td><span>" + (sharing.EmailList['Email4'] === "true" ? student.Email4 : '本人未公開資訊') + "</span></td>\n</tr>\n<tr>\n	<th class=\"myth\"><span>Email5</span></th>\n	<td><span>" + (sharing.EmailList['Email5'] === "true" ? student.Email5 : '本人未公開資訊') + "</span></td>\n</tr>");
  };

}).call(this);
