// Generated by CoffeeScript 1.6.2
(function() {
  var getSelectionSubject, global;

  global = {};

  $(document).ready(function() {
    gadget.getContract("ischool.course_selection.public").send({
      service: "default.GetSelectionSemester",
      result: function(response, error, xhr) {
        return $("#message").html("開放選課時間：" + response.Response.StartTime + " ~ " + response.Response.EndTime);
      }
    });
    return gadget.getContract("ischool.course_selection.student").send({
      service: "default.GetMyGradeYear",
      result: function(response, error, xhr) {
        global.schoolYear = parseInt(response.Response.SelectionSchoolYear, 10);
        global.semester = parseInt(response.Response.SelectionSemester, 10);
        global.gradeYear = parseInt(response.Response.SelectionSchoolYear, 10) - parseInt(response.Response.CurrentSchoolYear, 10) + parseInt(response.Response.GradeYear, 10);
        return getSelectionSubject();
      }
    });
  });

  getSelectionSubject = function() {
    $("#content").html("");
    return gadget.getContract("ischool.course_selection.student").send({
      service: "default.GetSelectionSubject",
      body: "<Request>\n	<SchoolYear>" + global.schoolYear + "</SchoolYear>\n	<Semester>" + global.semester + "</Semester>\n	<GradeYear>" + global.gradeYear + "</GradeYear>\n</Request>",
      result: function(response, error, xhr) {
        var groups;

        groups = [];
        $(response.Response.Subject).each(function() {
          if ($.inArray(this.Group, groups) === -1) {
            return groups.push(this.Group);
          }
        });
        global.groups = groups;
        global.subjects = {};
        $(groups).each(function(i, group) {
          var selection_subject;

          $("<div id='group_" + group + "' style='margin:10px;display:inline-block'></div>").appendTo($("#content"));
          global.subjects[group] = [];
          selection_subject = [];
          $(response.Response.Subject).each(function() {
            this.Selection = this.SelectionID !== "" ? "checked='checked'" : "";
            this.FullName = "" + this.SubjectName + " " + this.Level;
            if (this.SelectionID !== "") {
              selection_subject.push(this.FullName);
            }
            if (this.Group === group) {
              return global.subjects[group].push(this);
            }
          });
          return $("#group_" + group).kendoGrid({
            dataSource: {
              data: global.subjects[group]
            },
            height: 560,
            scrollable: true,
            columns: [
              {
                field: "GradeYear",
                title: "年級",
                width: 60
              }, {
                field: "Semester",
                title: "學期",
                width: 60
              }, {
                field: "FullName",
                title: "完整課程名稱",
                width: 240
              }, {
                field: "Credit",
                title: "學分",
                width: 60
              }, {
                field: "Type",
                title: "課程類別",
                width: 120
              }, {
                field: "Limit",
                title: "修課上限",
                width: 90
              }, {
                field: "SelectionCount",
                title: "已選人數",
                width: 90
              }, {
                field: "Selection",
                title: "選取",
                width: 60,
                template: '<input type="checkbox" subject-id="#= SubjectID #" group="#= Group #" #= Selection #/>'
              }
            ],
            detailTemplate: kendo.template("<div class='tabstrip'>\n	<ul>\n		<li class='k-state-active'>教學目標</li>\n		                        <li>教學內容</li>\n		                        <li>備註</li>\n		                    </ul>\n		                    <div><div style='margin:10px'>#= Goal #</div></div>\n		                    <div><div style='margin:10px'>#= Content #</div></div>\n		                    <div><div style='margin:10px'>#= Memo #</div></div>\n		                </div>"),
            dataBound: function() {
              return this.expandRow(this.tbody.find("tr.k-master-row"));
            },
            detailInit: function(e) {
              return e.detailRow.find(".tabstrip").kendoTabStrip({
                animation: {
                  open: {
                    effects: "fadeIn"
                  }
                }
              });
            },
            toolbar: kendo.template("<div class='toolbar'>\n		                    <span style='float:right'>" + group + " 群組課程 " + global.subjects[group].length + " 選 " + global.subjects[group][0].CountLimit + "</span>\n		                    <span group='" + group + "' style='float:right;margin-right:20px;color:red'></span>\n		                    <button class='k-button' group='" + group + "' count-limit='" + global.subjects[group][0].CountLimit + "'>送出選課</button>\n		                    <span style='color:blue'>已選課程：" + (selection_subject.join(", ")) + "</span>\n		                </div>")
          });
        });
        $("button").unbind("click");
        return $("button").click(function() {
          var group, message, subject, subject_id, subject_id_list;

          subject_id = [];
          subject_id_list = [];
          $("input[type=checkbox][group=" + ($(this).attr('group')) + "]").each(function() {
            if ($(this).attr("checked") != null) {
              subject_id.push($(this).attr("subject-id"));
            }
            return subject_id_list.push($(this).attr("subject-id"));
          });
          group = $(this).attr("group");
          message = "" + group + " 所選課程如下：\n\n";
          $(global.subjects[group]).each(function(i, subject) {
            return $(subject_id).each(function(j, id) {
              if (subject.SubjectID === id) {
                return message += "" + subject.FullName + "\n";
              }
            });
          });
          if (subject_id.length !== parseInt($(this).attr("count-limit"), 10)) {
            $("span[group=" + group + "]").html("此群組課程必須或僅能選取 " + (parseInt($(this).attr('count-limit'), 10)) + " 門課");
            return alert("此群組課程必須或僅能選取 " + (parseInt($(this).attr('count-limit'), 10)) + " 門課");
          } else {
            subject = "";
            $(subject_id).each(function() {
              return subject += "<Subject>\n	<SubjectID>" + this + "</SubjectID>\n	<SubjectIDList>" + (subject_id_list.join()) + "</SubjectIDList>\n</Subject>";
            });
            return gadget.getContract("ischool.course_selection.student").send({
              service: "default.AddSelectionSubject",
              body: "<Request>\n	" + subject + "\n</Request>",
              result: function(response, error, xhr) {
                var _ref;

                if ((error != null ? (_ref = error.dsaError) != null ? _ref.status : void 0 : void 0) === '504') {
                  return $("span[group=" + group + "]").html(error.dsaError.message);
                } else {
                  if (parseInt(response.Result.EffectRows, 10) === subject_id.length) {
                    getSelectionSubject();
                    return alert("" + message + "\n此群組選課完成");
                  }
                }
              }
            });
          }
        });
      }
    });
  };

}).call(this);
