// Generated by CoffeeScript 1.3.1
(function() {
  var getClassStudents, getStudentSelectionSubject, global;

  global = {};

  $(function() {
    return gadget.getContract("ischool.course_selection.teacher").send({
      service: "default.GetDeptClasses",
      result: function(response, error, xhr) {
        var items;
        items = "";
        $(response.Response.Class).each(function() {
          if (this.Current === "true") {
            return items += "<li><a href='#' class-id='" + this.ClassID + "'>" + this.ClassName + "</a></li>";
          }
        });
        $("#class-list").html(items);
        return $("#class-list a").click(function(e) {
          e.preventDefault();
          $("#class-title").html("" + ($(this).html()) + " <span class='caret'></span>");
          global.class_id = $(this).attr("class-id");
          return getClassStudents();
        });
      }
    });
  });

  getClassStudents = function() {
    $("#student-info").html("");
    $("#subject-list").html("");
    return gadget.getContract("ischool.course_selection.teacher").send({
      service: "default.GetClassStudents",
      body: "<Request><ClassID>" + global.class_id + "</ClassID></Request>",
      result: function(response, error, xhr) {
        var items;
        global.students = $(response.Response.Student);
        items = "";
        $(response.Response.Student).each(function(index, student) {
          return items += "<tr index='" + index + "'>\n	<td>" + student.StudentNumber + "</td>\n	<td>" + student.SeatNo + "</td>\n	<td>" + student.Name + "</td>\n	<td>" + student.Gender + "</td>\n	<td>" + (student.SubjectName.replace(/\"/gm, '').replace(/{/gm, '').replace(/}/gm, '').replace(/NULL/gm, '').replace(/,/gm, '<br/>')) + "</td>\n	<td><a href='#' index='" + index + "'>詳細</a></td>\n</tr>";
        });
        $("#student-list tbody").html(items);
        return $("#student-list tbody tr a").click(function(e) {
          e.preventDefault();
          global.student = global.students[$(this).attr("index")];
          return getStudentSelectionSubject();
        });
      }
    });
  };

  getStudentSelectionSubject = function() {
    $("#student-info").html("<div class='alert'>" + global.student.SeatNo + " " + global.student.Name + "</div>");
    $("#subject-list").html("");
    return gadget.getContract("ischool.course_selection.teacher").send({
      service: "default.GetStudentGradeYear",
      body: "<Request>\n	<StudentID>" + global.student.ID + "</StudentID>\n</Request>",
      result: function(response, error, xhr) {
        var gradeYear;
        if ((response != null ? response.Response : void 0) != null) {
          gradeYear = parseInt(response.Response.SelectionSchoolYear, 10) - parseInt(response.Response.CurrentSchoolYear, 10) + parseInt(response.Response.GradeYear, 10);
          if ($("#upgrade").attr("checked") === "checked") {
            gradeYear -= 1;
          }
          return gadget.getContract("ischool.course_selection.teacher").send({
            service: "default.GetStudentSelectionSubject",
            body: "<Request>\n	<SchoolYear>" + response.Response.SelectionSchoolYear + "</SchoolYear>\n	<Semester>" + response.Response.SelectionSemester + "</Semester>\n	<GradeYear>" + gradeYear + "</GradeYear>\n	<StudentID>" + global.student.ID + "</StudentID>\n</Request>",
            result: function(response, error, xhr) {
              global.groups = [];
              global.subjects = [];
              $(response.Response.Subject).each(function() {
                if ($.inArray(this.Group, global.groups) === -1) {
                  global.groups.push(this.Group);
                }
                return global.subjects[this.Group] = [];
              });
              return $(global.groups).each(function(i, group) {
                var items;
                $(response.Response.Subject).each(function() {
                  this.FullName = "" + this.SubjectName + " " + this.Level;
                  this.Selection = this.SelectionID !== "" ? "checked='checked'" : "";
                  if (this.Group === group) {
                    return global.subjects[group].push(this);
                  }
                });
                items = "";
                $(global.subjects[group]).each(function() {
                  return items += "<tr>\n	<td>" + this.FullName + "</td>\n	<td>" + this.Limit + "</td>\n	<td>" + this.SelectionCount + "</td>\n	<td><input type='checkbox' subject-id='" + this.SubjectID + "' group='" + this.Group + "' " + this.Selection + "/></td>\n</tr>";
                });
                $("#subject-list").append("<div>\n	<div class='btn-toolbar'>\n		<a href='#' class='btn btn-inverse set-subject' group='" + group + "' count-limit='" + global.subjects[group][0].CountLimit + "'>調整</a>\n		<span class='btn btn-info disabled pull-right'>" + group + "  (" + global.subjects[group].length + " 選 " + global.subjects[group][0].CountLimit + ")</span>\n	</div>\n	<table class='table table-bordered'>\n		<thead>\n			<tr>\n				<th>課程名稱</th>\n				<th>修課上限</th>\n				<th>已選人數</th>\n				<th>選課</th>\n			</tr>\n		</thead>\n		<tbody>" + items + "</tbody>\n	</table>\n</div>");
                $("#subject-list .set-subject").unbind("click");
                return $("#subject-list .set-subject").click(function() {
                  var message, subject, subject_id, subject_id_list;
                  subject_id = [];
                  subject_id_list = [];
                  $("input[type=checkbox][group=" + ($(this).attr('group')) + "]").each(function() {
                    if ($(this).attr("checked") != null) {
                      subject_id.push($(this).attr("subject-id"));
                    }
                    return subject_id_list.push($(this).attr("subject-id"));
                  });
                  group = $(this).attr("group");
                  message = "" + group + " 所選課程如下：\n\n";
                  $(global.subjects[group]).each(function(i, subject) {
                    return $(subject_id).each(function(j, id) {
                      if (subject.SubjectID === id) {
                        return message += "" + subject.FullName + "\n";
                      }
                    });
                  });
                  if (subject_id.length !== parseInt($(this).attr("count-limit"), 10)) {
                    return alert("此群組課程必須或僅能選取 " + (parseInt($(this).attr('count-limit'), 10)) + " 門課");
                  } else {
                    subject = "";
                    $(subject_id).each(function() {
                      return subject += "<Subject>\n	<StudentID>" + global.student.ID + "</StudentID>\n	<SubjectID>" + this + "</SubjectID>\n	<SubjectIDList>" + (subject_id_list.join()) + "</SubjectIDList>\n</Subject>";
                    });
                    return gadget.getContract("ischool.course_selection.teacher").send({
                      service: "default.SetStudentSelectionSubject",
                      body: "<Request>\n	" + subject + "\n</Request>",
                      result: function(response, error, xhr) {
                        var _ref;
                        if ((error != null ? (_ref = error.dsaError) != null ? _ref.status : void 0 : void 0) === '504') {
                          return alert(error.dsaError.message);
                        } else {
                          if (parseInt(response.Result.EffectRows, 10) === subject_id.length) {
                            getClassStudents();
                            getStudentSelectionSubject();
                            return alert("" + message + "\n此群組選課完成");
                          }
                        }
                      }
                    });
                  }
                });
              });
            }
          });
        }
      }
    });
  };

}).call(this);
